In [ ]:
print(100)

100

In [ ]:
print(15.55)

15.55

In [ ]:
print('data science')

data science

**Type Casting or Type Conversions**

Type Conversions means converting one data type into another data type

* int -> float and int -> str
* float -> int and float -> str
* str -> int and str -> float =>***

In [ ]:
# int-> float
a = 25
print(a)
print(type(a))

b = float(a)
print(b)
print(type(b))

25
<class 'int'>
25.0
<class 'float'>

In [ ]:
a = 55
str(a)

'55'

In [ ]:
# int -> str
a = 25 # saving in the memory
print(a) # calling from the memory
print(type(a)) # type is used to find that variable is holding which data type

b = str(a) # Actual conversion going here
print(b)
print(type(b))

25
<class 'int'>
25
<class 'str'>

In [ ]:
# float -> int
a = 25.55
print(a)
print(type(a))

b = int(a)
print(b)
print(type(b))

25.55
<class 'float'>
25
<class 'int'>

In [ ]:
# float -> str
a = 25.55
print(a)
print(type(a))

b = str(a)
print(b)
print(type(b))

25.55
<class 'float'>
25.55
<class 'str'>

In [ ]:
# str -> int
a = '25'
print(a)
print(type(a))

b = int(a)
print(b)
print(type(b))

25
<class 'str'>
25
<class 'int'>

In [ ]:
a = 'vizag'
print(a)
print(type(a))

b = int(a)
print(a)
print(type(b))

vizag
<class 'str'>

ValueError: invalid literal for int() with base 10: 'vizag'

In [ ]:
# str -> float
a = '25'
print(a)
print(type(a))

b = float(a)
print(b)
print(type(b))

25
<class 'str'>
25.0
<class 'float'>

In [ ]:
a = 'chennai25.5'
print(a)
print(type(a))

b = float(a)
print(b)
print(type(b))

chennai25.5
<class 'str'>

ValueError: could not convert string to float: 'chennai25.5'

In [ ]:
# built_in_words
import keyword # open library
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [ ]:
# math library
import math

In [ ]:
math.factorial(5)

120

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.sqrt(25)

5.0

In [ ]:
# sklearn
import sklearn

In [ ]:
print('My age is 12')

My age is 12

to make the relationship with one data type with other data type inside the  print -> to do this task we have 4 ways

* rule no.1 : using , comma  ->  we can add one data type with other data type and will also generate one tab space  ->  30%
* rule no.2 : using +    ->  we can add data types but make sure all are strings and also one tab space is not given
* rule no.3 : it works with shortcuts  ->  int %d , float %f , str %s
* rule no.4 : using f and {}  ->  real time using one

In [ ]:
print('My age is 12')

My age is 12

In [ ]:
# rule no.1 -> ,
a = 12
print('My age is',a)

My age is 12

In [ ]:
location = 'USA'
cost = 45000
ticket = 90000
print('I got college seat in',location,'which cost',cost,'and flight ticket was',ticket)

I got college seat in USA which cost 45000 and flight ticket was 90000

In [ ]:
# rule no.2 -> +
a = 12
print('My age is '+str(a))

My age is 12

In [ ]:
location = 'USA'
cost = 45000
ticket = 90000
print('I got college seat in '+location+ ' which cost '+str(cost)+ ' and flight ticket was '+str(ticket))

I got college seat in USA which cost 45000 and flight ticket was 90000

In [ ]:
# rule no.3 -> %d,%f,%s
a = 12
print('My age is %d' %(a))

My age is 12

In [ ]:
location = 'USA'
cost = 45000
ticket = 90000.55
print('I got college seat in %s which cost %d and flight ticket was %f'%(location,cost,ticket))

I got college seat in USA which cost 45000 and flight ticket was 90000.550000

In [ ]:
# rule no.4 -> f and {}
a = 12
print(f'My age is {a}')

My age is 12

In [ ]:
location = 'USA'
cost = 45000
ticket = 90000
print(f'I got college seat in {location} which cost {cost} and flight ticket was {ticket}')

I got college seat in USA which cost 45000 and flight ticket was 90000

In [ ]:
print(math.factorial(5))

120

In [ ]:
print(f'The factorial of a given number is : {math.factorial(5)}')

The factorial of a given number is : 120

In [ ]:
a = 120
print(f'The factorial of a given number is : {a}')

The factorial of a given number is : 120

In [ ]:
print(f'The factorial of a given number is : {120}')

The factorial of a given number is : 120

In [ ]:
print(f'My name is syamala and my output is : {int(math.factorial(10)/math.pi)}')

My name is syamala and my output is : 1155082